version: 0.0
os: linux
files:
  - source: /web
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: ec2-user
    group: apache
hooks:
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root
