version: 0.0
os: linux
files:
  - source: /web
    destination: /var/www/html
hooks:
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root
